'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { App } from 'antd';
import "./globals.css";
import React, { Suspense } from "react";
import { Providers } from "@/utils/redux/provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Suspense fallback={<div>Loading...</div>}>
            <App>
              {children}
            </App>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
